spring.datasource.url=jdbc:postgresql://localhost:5432/data_treasure
spring.datasource.username=data_treasure
spring.datasource.password=data_treasure_password

spring.flyway.url=jdbc:postgresql://localhost:5432/data_treasure
spring.flyway.user=data_treasure
spring.flyway.password=data_treasure_password
